// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using csye6225.Models;

namespace csye6225.Migrations
{
    [DbContext(typeof(dbContext))]
    [Migration("20200210205640_bill_attachment")]
    partial class bill_attachment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("csye6225.Models.AccountModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("account_created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("account_updated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("email_address")
                        .HasColumnType("text");

                    b.Property<string>("first_name")
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("csye6225.Models.BillModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("amount_due")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("attachment")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("bill_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("categories")
                        .HasColumnType("text");

                    b.Property<DateTime?>("created_ts")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("owner_id")
                        .HasColumnType("uuid");

                    b.Property<int>("payment_status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("updated_ts")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("vendor")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("csye6225.Models.FileModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("file_ext")
                        .HasColumnType("text");

                    b.Property<string>("file_name")
                        .HasColumnType("text");

                    b.Property<long>("file_size")
                        .HasColumnType("bigint");

                    b.Property<int>("hash_code")
                        .HasColumnType("integer");

                    b.Property<DateTime>("upload_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("url")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("File");
                });
#pragma warning restore 612, 618
        }
    }
}
